force-app/main/default/objects/BMX_Audits_Schedule__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Revision #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BMX_Audits_Schedule__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Already_Audited__c.field-meta.xml
<CustomField>
    <fullName>Already_Audited__c</fullName>
    <label>Previously Audited</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes-in TWD</fullName>
            </value>
            <value>
                <fullName>Yes-not in TWD</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Objectives__c.field-meta.xml
<CustomField>
    <fullName>Audit_Objectives__c</fullName>
    <label>Audit Objectives</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Quality Audits</relationshipLabel>
    <relationshipName>Quality_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Lead_Auditor__c.field-meta.xml
<CustomField>
    <fullName>Lead_Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Origination__c.field-meta.xml
<CustomField>
    <fullName>Origination__c</fullName>
    <formula>TEXT( Audit_Schedule__r.Origination__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origination</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Reason_for_Audit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Audit__c</fullName>
    <label>Reason for Audit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Certification Audit</fullName>
            </value>
            <value>
                <fullName>Follow-up Audit</fullName>
            </value>
            <value>
                <fullName>For Cause audit</fullName>
            </value>
            <value>
                <fullName>Mock Inspection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Priority Audit</fullName>
            </value>
            <value>
                <fullName>Qualification Audit</fullName>
            </value>
            <value>
                <fullName>Re-audit</fullName>
            </value>
            <value>
                <fullName>Routine audit</fullName>
            </value>
            <value>
                <fullName>Special request from Management</fullName>
            </value>
            <value>
                <fullName>&quot;Technical&quot; Audit (wording to be confirmed)</fullName>
                <label>Technical Audit</label>
            </value>
            <value>
                <fullName>Unannounced audit;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Revision_History__c/Revision_History__c.object-meta.xml
<CustomObject>
    <label>Revision History</label>
    <nameField>
        <displayFormat>RevH-{0000000}</displayFormat>
        <label>Revision History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revision Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revision_History__c/fields/Audit_Schedule_Number__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule_Number__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Revision Table</relationshipLabel>
    <relationshipName>Revision_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revision_History__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revision_History__c/fields/Schedule_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Change_Reason__c</fullName>
    <label>Schedule Change reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Addition of an Audit</fullName>
            </value>
            <value>
                <fullName>Cancellation of an Audit</fullName>
            </value>
            <value>
                <fullName>Change in the Audited site</fullName>
            </value>
            <value>
                <fullName>Change in the Audit method</fullName>
            </value>
            <value>
                <fullName>Change in the Audit objectives</fullName>
            </value>
            <value>
                <fullName>Change in the Audit scheduled quarter</fullName>
            </value>
            <value>
                <fullName>Change in the Audit title</fullName>
            </value>
            <value>
                <fullName>Change of the Reason for Audit</fullName>
            </value>
            <value>
                <fullName>Creation of the schedule</fullName>
            </value>
            <value>
                <fullName>Yearly focus objectives of the schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <customValue>
        <fullName>2032</fullName>
    </customValue>
    <customValue>
        <fullName>2033</fullName>
    </customValue>
    <customValue>
        <fullName>2034</fullName>
    </customValue>
    <customValue>
        <fullName>2035</fullName>
    </customValue>
    <customValue>
        <fullName>2036</fullName>
    </customValue>
    <customValue>
        <fullName>2037</fullName>
    </customValue>
    <customValue>
        <fullName>2038</fullName>
    </customValue>
    <customValue>
        <fullName>2039</fullName>
    </customValue>
    <customValue>
        <fullName>2040</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/Audit_ScheduleTriggerHandlerTest.cls
@isTest
public class Audit_ScheduleTriggerHandlerTest {
    @TestSetup
    static void makeData(){
         Profile p = [select id from profile where name='BMX TWD User'];
        
        User u = new User(alias = 'utest', email='utest@email.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id, country='United States',
                          timezonesidkey='America/Los_Angeles', username='utest21@email.com',TWD_Role__c='Audit Coordinator');
       insert u;
        
        Id internalRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id externeRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();
        
        Id qualityAuditInternalRecordTypeId = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id qualityAuditexterneRecordTypeId = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();

        BMX_Audits_Schedule__c Audits_Schedule = new BMX_Audits_Schedule__c();     
        Audits_Schedule.RecordTypeId = internalRecordTypeId;
        Audits_Schedule.Title__c = 'TEst';
        //Audits_Schedule.Origination__c = 'TEst';
        Audits_Schedule.Year__c = '2022';
        //Audits_Schedule.Scope__c = 'TEst';
        Audits_Schedule.CMPL123_WF_Status__c = 'Initiated';
        Audits_Schedule.Scope__c = 'Local';
        insert Audits_Schedule;
       
        /*
        BMX_Audits_Schedule__c Audits_Schedule2 = new BMX_Audits_Schedule__c();     
        Audits_Schedule2.RecordTypeId = externeRecordTypeId;
        Audits_Schedule2.Title__c = 'TEst';
        //Audits_Schedule2.Origination__c = 'TEst';
        Audits_Schedule2.Year__c = '2022';
        //Audits_Schedule2.Scope__c = 'TEst';
        Audits_Schedule.CMPL123_WF_Status__c = 'test';
        Audits_Schedule.Scope__c = 'Distributor';
        Insert Audits_Schedule2;
		*/
         BMX_Audits_Schedule__c auditSchedule3 = new BMX_Audits_Schedule__c(
            RecordTypeId = externeRecordTypeId,
            Title__c = 'Test External',
            Scope__c = 'Distributor',
            CMPL123_WF_Status__c = 'Audit Schedule Definition'
             
       );
        insert auditSchedule3;
        
        
		BMX_Quality_Audit__c qualityAudit = new BMX_Quality_Audit__c();
        qualityAudit.RecordTypeId = qualityAuditInternalRecordTypeId;
        qualityAudit.Title__c = 'test';
        qualityAudit.Year__c = '2022';
        qualityAudit.Already_Audited__c = 'No';
        qualityAudit.Audit_Schedule__c = Audits_Schedule.Id;
        insert qualityAudit;
        
        BMX_Quality_Audit__c qualityAudit2 = new BMX_Quality_Audit__c();
        qualityAudit2.RecordTypeId = qualityAuditexterneRecordTypeId;
        qualityAudit2.Title__c = 'test';
        qualityAudit2.Year__c = '2022';
        qualityAudit2.Already_Audited__c = 'No';
        qualityAudit2.Audit_Schedule__c = Audits_Schedule.Id;
        insert qualityAudit2;
        
         BMX_Quality_Audit__c qualityAudit3 = new BMX_Quality_Audit__c(
            Audit_Schedule__c = auditSchedule3.Id,
            RecordTypeId = qualityAuditexterneRecordTypeId,
            CMPL123_WF_Status__c = 'Initiated',
            Lead_Auditor__c = u.Id,
            Reason_for_Audit__c = 'Other',
            Audit_Objectives__c = 'Audit'
            
        );
        insert qualityAudit3;   
        
        Revision_History__c revHis = new Revision_History__c();
        revHis.Audit_Schedule_Number__c =  auditSchedule3.Id;
        revHis.Revision__c = null;
        revHis.Schedule_Change_Reason__c = 'Creation of the schedule';
        Insert revHis;
        
        
  		/*
        QMS_Task__c task = new QMS_Task__c();
        task.CMPL123_WF_Status__c = 'TEST';
        task.Cause_Investigation__c = Audit_Finding.Id;
        task.Title__c = '';
        insert task;
		*/
    }
    @isTest
    public static void handleAfterUpdate(){
        Map<Id,BMX_Audits_Schedule__c> Audits_ScheduleMap = new Map<Id,BMX_Audits_Schedule__c>([SELECT Id,CMPL123_WF_Status__c,RecordType.DeveloperName FROM BMX_Audits_Schedule__c LIMIT 1]);
        BMX_Audits_Schedule__c audit = Audits_ScheduleMap.values()[0];
        audit.CMPL123_WF_Status__c = 'Audit Schedule Implementation';
        update audit;
        Map<Id,BMX_Audits_Schedule__c> newAuditScheMap = new Map<Id,BMX_Audits_Schedule__c>();
        newAuditScheMap.put(audit.Id, audit);
        Audit_ScheduleTriggerHandler.handleAfterUpdate(Audits_ScheduleMap,newAuditScheMap);
    }
    @isTest
    public static void testhandleBeforeUpdate(){
        Map<Id,BMX_Audits_Schedule__c> Audits_ScheduleMap = new Map<Id,BMX_Audits_Schedule__c>([SELECT Id,CMPL123_WF_Status__c,RecordType.DeveloperName,CMPL123_WF_Action__c,Scope__c FROM BMX_Audits_Schedule__c WHERE CMPL123_WF_Status__c = 'Audit Schedule Definition']);
        BMX_Audits_Schedule__c audit = Audits_ScheduleMap.values()[0];
        System.debug('audit ' + audit);
        audit.CMPL123_WF_Action__c = 'Send for Approval';
        
        Test.StartTest();      
        update audit; 
        Test.StopTest();
        
        //BMX_Audits_Schedule__c audit2 = Audits_ScheduleMap.values()[1];
        //audit2.CMPL123_WF_Action__c = 'Send for Approval';
        //audit2.Scope__c = 'Distributor';
        //update audit2;
		
        Map<Id,BMX_Audits_Schedule__c> newAuditScheMap = new Map<Id,BMX_Audits_Schedule__c>();
        newAuditScheMap.put(audit.Id, audit);
        //newAuditScheMap.put(audit2.Id,audit2);
        Audit_ScheduleTriggerHandler.handleBeforeUpdate(Audits_ScheduleMap,newAuditScheMap);
    }
        @isTest
    public static void auditsScheduleT(){
        Id internalRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        BMX_Audits_Schedule__c auditSchedule1 = new BMX_Audits_Schedule__c() ;
        auditSchedule1.CMPL123_WF_Status__c = 'Initiated';
        insert auditSchedule1;
       
 			BMX_Quality_Audit__c qualityAudit = new BMX_Quality_Audit__c(
            Audit_Schedule__c = auditSchedule1.Id,
            CMPL123_WF_Status__c = Label.Status_Report_Approved      
        );
        insert qualityAudit;
        BMX_Audits_Schedule__c auditSchedule2 = new BMX_Audits_Schedule__c() ;
        auditSchedule1.CMPL123_WF_Status__c = 'Initiated';
        insert auditSchedule2;
       
 			BMX_Quality_Audit__c qualityAudit2 = new BMX_Quality_Audit__c(
            Audit_Schedule__c = auditSchedule2.Id,
            CMPL123_WF_Status__c = Label.Status_Closed_Done
            
                
        );
        insert qualityAudit2;
        Test.StartTest();  
        auditSchedule1.CMPL123_WF_Status__c = System.Label.Status_Audit_Schedule_Implementation;
        update auditSchedule1; 
        auditSchedule2.CMPL123_WF_Status__c = System.Label.Status_Audit_Schedule_Executed;
        update auditSchedule2; 
        Test.StopTest();
    
}
    
}