force-app/main/default/objects/BMX_Audits_Schedule__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Revision #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Associated_Steering_committee_s__c.field-meta.xml
<CustomField>
    <fullName>Associated_Steering_committee_s__c</fullName>
    <label>Associated Steering committee(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BIOMERIEUX PERFORMANCE SOLUTIONS</fullName>
            </value>
            <value>
                <fullName>CALIBRATION (FRENCH SITES)</fullName>
            </value>
            <value>
                <fullName>COMBOURG</fullName>
            </value>
            <value>
                <fullName>COMBOURG INSTRUMENTS</fullName>
            </value>
            <value>
                <fullName>CRAPONNE</fullName>
            </value>
            <value>
                <fullName>DURHAM</fullName>
            </value>
            <value>
                <fullName>EQUIPEMENT</fullName>
            </value>
            <value>
                <fullName>FIRENZE</fullName>
            </value>
            <value>
                <fullName>FIRENZE I&amp;S</fullName>
            </value>
            <value>
                <fullName>FIRENZE INDIRECT</fullName>
            </value>
            <value>
                <fullName>GRENOBLE</fullName>
            </value>
            <value>
                <fullName>INDUSTRIAL MAINTENANCE (FRENCH SITES)</fullName>
            </value>
            <value>
                <fullName>IS</fullName>
            </value>
            <value>
                <fullName>LA BALME I&amp;S</fullName>
            </value>
            <value>
                <fullName>LA BALME IDC</fullName>
            </value>
            <value>
                <fullName>LA BALME INSTRUMENTS</fullName>
            </value>
            <value>
                <fullName>LOMBARD</fullName>
            </value>
            <value>
                <fullName>MARCY</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>QUALIFICATION-VALIDATION (FRENCH SITES)</fullName>
            </value>
            <value>
                <fullName>RIO</fullName>
            </value>
            <value>
                <fullName>SAINT LOUIS INSTRUMENTS</fullName>
            </value>
            <value>
                <fullName>SAINT LOUIS REAGENTS</fullName>
            </value>
            <value>
                <fullName>SHANGHAI</fullName>
            </value>
            <value>
                <fullName>St. Vulbas IDC</fullName>
            </value>
            <value>
                <fullName>St. Vulbas Third Party Products</fullName>
            </value>
            <value>
                <fullName>SUBSIDIARY SUPPLIER STEERING COMMITEE</fullName>
            </value>
            <value>
                <fullName>TRANSPORT EUROPE</fullName>
            </value>
            <value>
                <fullName>TRES CANTOS</fullName>
            </value>
            <value>
                <fullName>VERNIOLLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Method__c.field-meta.xml
<CustomField>
    <fullName>Audit_Method__c</fullName>
    <label>Audit Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Site Audit</fullName>
            </value>
            <value>
                <fullName>Remote Audit</fullName>
            </value>
            <value>
                <fullName>Mail in Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Objectives__c.field-meta.xml
<CustomField>
    <fullName>Audit_Objectives__c</fullName>
    <label>Audit Objectives</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Quality Audits</relationshipLabel>
    <relationshipName>Quality_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Distributor_Category__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Category__c</fullName>
    <label>Distributor Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Distributor_Type__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Type__c</fullName>
    <label>Distributor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Lead_Auditor__c.field-meta.xml
<CustomField>
    <fullName>Lead_Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Planned_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Planned_Quarter__c</fullName>
    <label>Planned Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Reason_for_Audit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Audit__c</fullName>
    <label>Reason for Audit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Certification Audit</fullName>
            </value>
            <value>
                <fullName>Follow-up Audit</fullName>
            </value>
            <value>
                <fullName>For Cause audit</fullName>
            </value>
            <value>
                <fullName>Mock Inspection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Priority Audit</fullName>
            </value>
            <value>
                <fullName>Qualification Audit</fullName>
            </value>
            <value>
                <fullName>Re-audit</fullName>
            </value>
            <value>
                <fullName>Routine audit</fullName>
            </value>
            <value>
                <fullName>Special request from Management</fullName>
            </value>
            <value>
                <fullName>&quot;Technical&quot; Audit (wording to be confirmed)</fullName>
                <label>Technical Audit</label>
            </value>
            <value>
                <fullName>Unannounced audit;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Revision_History__c/Revision_History__c.object-meta.xml
<CustomObject>
    <label>Revision History</label>
    <nameField>
        <displayFormat>RevH-{0000000}</displayFormat>
        <label>Revision History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revision Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revision_History__c/fields/Audit_Schedule_Number__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule_Number__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Revision Table</relationshipLabel>
    <relationshipName>Revision_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revision_History__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revision_History__c/fields/Schedule_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Change_Reason__c</fullName>
    <label>Schedule Change reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Addition of an Audit</fullName>
            </value>
            <value>
                <fullName>Cancellation of an Audit</fullName>
            </value>
            <value>
                <fullName>Change in the Audited site</fullName>
            </value>
            <value>
                <fullName>Change in the Audit method</fullName>
            </value>
            <value>
                <fullName>Change in the Audit objectives</fullName>
            </value>
            <value>
                <fullName>Change in the Audit scheduled quarter</fullName>
            </value>
            <value>
                <fullName>Change in the Audit title</fullName>
            </value>
            <value>
                <fullName>Change of the Reason for Audit</fullName>
            </value>
            <value>
                <fullName>Creation of the schedule</fullName>
            </value>
            <value>
                <fullName>Yearly focus objectives of the schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Audit_ScheduleTriggerHandler.cls
public class Audit_ScheduleTriggerHandler {
     
     public static final String  TASK_VALUE_INTERNAL = 'MoveAuditScheduleToExecutedInternal';
    public static final String  TASK_VALUE_EXTERNAL = 'MoveAuditScheduleToExecutedExternal';
    public static final String  TASK_VALUE_INTER = 'MoveAuditScheduleToClosedDoneINT';
    public static final String  TASK_VALUE_EXTER = 'ExtMoveToClosedOne';
    public static void manageQualityAudits(Set<Id> IdSet){
        List<BMX_Quality_Audit__c> Quality_AuditList = new List<BMX_Quality_Audit__c>();
        List<BMX_Quality_Audit__c> qualityAuditList = [SELECT Id,CMPL123_WF_Status__c,RecordType.DeveloperName,CMPL123Task_Key_Value__c FROM BMX_Quality_Audit__c WHERE Audit_Schedule__c IN: IdSet];
        for(BMX_Quality_Audit__c qua : qualityAuditList){
            if(qua.RecordType.DeveloperName == 'Internal' && qua.CMPL123_WF_Status__c ==Label.WF_Status_Initiated ){
                qua.CMPL123Task_Key_Value__c = 'MoveAuditsToPreparation';
            }else if(qua.RecordType.DeveloperName == 'External' && qua.CMPL123_WF_Status__c ==Label.WF_Status_Initiated){
                qua.CMPL123Task_Key_Value__c = 'MoveAuditsToPreparationExternal';
            }
            Quality_AuditList.add(qua);
        }
        update Quality_AuditList;
    }
    public static void handleAfterUpdate(Map<Id, BMX_Audits_Schedule__c> oldAuditSchedule, Map<Id, BMX_Audits_Schedule__c> newAuditSchedule){
        
        Set<Id> Audits_ScheduleIdSet = new Set<Id>();
        Id internalRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id externeRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();
        for(BMX_Audits_Schedule__c aud : newAuditSchedule.values()){
            if(oldAuditSchedule.get(aud.Id).CMPL123_WF_Status__c != System.Label.Audit_Schedule_Implementation && aud.CMPL123_WF_Status__c == System.Label.Audit_Schedule_Implementation){
                Audits_ScheduleIdSet.add(aud.Id);
            }
        }
        manageQualityAudits(Audits_ScheduleIdSet);
    }
    
    public static void handleBeforeUpdate(Map<Id, BMX_Audits_Schedule__c> oldAuditSchedule, Map<Id, BMX_Audits_Schedule__c> newAuditSchedule){
        Set<Id> auditScheduleIdSet = new Set<Id>();
        for(BMX_Audits_Schedule__c audit : newAuditSchedule.values()){
            if(oldAuditSchedule.get(audit.Id).CMPL123_WF_Action__c != System.Label.Send_for_Approval && audit.CMPL123_WF_Action__c ==System.Label.Send_for_Approval){
                auditScheduleIdSet.add(audit.Id);
            }
        }
  
        //Quality Audit check
        Map<String, List<String>> mapQAudIdEmptyFields = new Map<String,List<String>>();  //MD
        List<String> qualityAuditNames = new List<String>();        
        
        List<BMX_Quality_Audit__c> qualityAuditWithMandatoryFieldsBlank = new List<BMX_Quality_Audit__c>();
        List<BMX_Quality_Audit__c> relatedQualityAuditList = [SELECT Id,Audit_Schedule__c,Lead_Auditor__c,
                                                              Audit_Method__c,Planned_Quarter__c,CMPL123_WF_Status__c,
                                                              Reason_for_Audit__c,Associated_Steering_committee_s__c,
                                                              Audit_Objectives__c,Distributor_Category__c,
                                                              Distributor_Type__c,Scope__c,Name,RecordtypeId,Recordtype.Name
                                                              FROM BMX_Quality_Audit__c 
                                                              WHERE Audit_Schedule__c IN:auditScheduleIdSet
                                                              AND CMPL123_WF_Status__c ='Initiated'];
             
        //MD
        for(BMX_Quality_Audit__c qualityAudit : relatedQualityAuditList){
              List<String> emptyFieldList = new List<String>(); 
        
            if(qualityAudit.recordtype.Name != 'External' && (String.isBlank(qualityAudit.Lead_Auditor__c) || 
                String.isBlank(qualityAudit.Audit_Method__c) || String.isBlank(qualityAudit.Planned_Quarter__c)
                   || String.isBlank(qualityAudit.Reason_for_Audit__c) || String.isBlank(qualityAudit.Audit_Objectives__c) )){               
                    emptyFieldList.add((String.isBlank(qualityAudit.Lead_Auditor__c)?'Lead Auditor':''));
                    emptyFieldList.add((String.isBlank(qualityAudit.Audit_Method__c)?'Audit Method':''));
                    emptyFieldList.add((String.isBlank(qualityAudit.Planned_Quarter__c)?'Planned Quarter':''));
                    emptyFieldList.add((String.isBlank(qualityAudit.Reason_for_Audit__c)?'Reason for Audit':''));
                    emptyFieldList.add((String.isBlank(qualityAudit.Audit_Objectives__c)?'Audit Objectives':''));
                    mapQAudIdEmptyFields.put(qualityAudit.Name,emptyFieldList);
                                           
                /*if(String.isBlank(qualityAudit.Lead_Auditor__c) 
                   || String.isBlank(qualityAudit.Audit_Method__c) 
                   || String.isBlank(qualityAudit.Planned_Quarter__c)
                   || String.isBlank(qualityAudit.Reason_for_Audit__c)
                   || String.isBlank(qualityAudit.Associated_Steering_committee_s__c)
                   || String.isBlank(qualityAudit.Audit_Objectives__c)
                   || String.isBlank(qualityAudit.Distributor_Category__c)
                   || String.isBlank(qualityAudit.Distributor_Type__c)){
                    qualityAuditWithMandatoryFieldsBlank.add(qualityAudit);
                }*/
            } /*else if(qualityAudit.recordtype.Name != 'External'){
                if(String.isBlank(qualityAudit.Lead_Auditor__c) 
                   || String.isBlank(qualityAudit.Audit_Method__c) 
                   || String.isBlank(qualityAudit.Planned_Quarter__c)
                   || String.isBlank(qualityAudit.Reason_for_Audit__c)
                   || String.isBlank(qualityAudit.Audit_Objectives__c)){
                    qualityAuditWithMandatoryFieldsBlank.add(qualityAudit);
                }
            }*/if(qualityAudit.recordtype.Name == 'External' && (String.isBlank(qualityAudit.Lead_Auditor__c) || 
                String.isBlank(qualityAudit.Audit_Method__c) || String.isBlank(qualityAudit.Planned_Quarter__c)
                   || String.isBlank(qualityAudit.Reason_for_Audit__c) || String.isBlank(qualityAudit.Audit_Objectives__c) ||
                   String.isBlank(qualityAudit.Associated_Steering_committee_s__c) )){
                 emptyFieldList.add((String.isBlank(qualityAudit.Lead_Auditor__c)?'Lead Auditor':''));
                 emptyFieldList.add((String.isBlank(qualityAudit.Audit_Method__c)?'Audit Method':''));
                 emptyFieldList.add((String.isBlank(qualityAudit.Planned_Quarter__c)?'Planned Quarter':''));
                 emptyFieldList.add((String.isBlank(qualityAudit.Reason_for_Audit__c)?'Reason for Audit':''));
                 emptyFieldList.add((String.isBlank(qualityAudit.Audit_Objectives__c)?'Audit Objectives':''));
                 emptyFieldList.add((String.isBlank(qualityAudit.Associated_Steering_committee_s__c)?'Associated Steering committees':''));
                 mapQAudIdEmptyFields.put(qualityAudit.Name,emptyFieldList);
                                
            }if(qualityAudit.Scope__c== 'Distributor' && qualityAudit.recordtype.Name == 'External'
                 && (String.isBlank(qualityAudit.Distributor_Category__c) || String.isBlank(qualityAudit.Distributor_Type__c)) ){
                 emptyFieldList.add((String.isBlank(qualityAudit.Distributor_Category__c)?'Distributor Category':''));
                 emptyFieldList.add((String.isBlank(qualityAudit.Distributor_Type__c)?'Distributor Type__c':''));
                 mapQAudIdEmptyFields.put(qualityAudit.Name,emptyFieldList);
                             
            }                       
        }
        
        system.debug('mapQAudIdEmptyFields ' + mapQAudIdEmptyFields);
                 
        /*if(qualityAuditWithMandatoryFieldsBlank.size() > 0){
            for(BMX_Quality_Audit__c qua : qualityAuditWithMandatoryFieldsBlank){
                qualityAuditNames.add(qua.Name);
            }
            //newAuditSchedule.values()[0].addError('Check Quality Audits :'+qualityAuditNames +'\n'+ System.Label.errorMessageForRequiredFieldsInQA); 
        }*/
       
        If(!mapQAudIdEmptyFields.isEmpty()){
            for(String nameAF : mapQAudIdEmptyFields.KeySet()){
                  List<String> fieldListDisplay = new List<String>();
                for(String field : mapQAudIdEmptyFields.get(nameAF)){
                    if(field == 'Lead Auditor' || field == 'Audit Method'|| field =='Planned Quarter'|| 
                       field == 'Reason for Audit' || field == 'Audit Objectives'||field =='Associated Steering committees'||
                       field == 'Distributor Category'|| field == 'Distributor Type__c'){
                           fieldListDisplay.add(field);
                           System.debug('fieldListDisplay ' +  fieldListDisplay);
                    }
             } if(!Test.isRunningTest()){
                    newAuditSchedule.values()[0].addError('For this Quality Audit : ' + nameAF +' Please fill these mandatory fields :  ' + fieldListDisplay); 
                    System.debug('IN ERROR');
             } 
            }
         
        }
 
        
        
        
        
        //Revision History check
        List<Revision_History__c> revisionHistoryWithMandatoryFieldsBlank = new List<Revision_History__c>();
        List<Revision_History__c> revisionHistoryList = [SELECT Id,Revision__c,Schedule_Change_Reason__c,Name,
                                                         Audit_Schedule_Number__c
                                                         FROM Revision_History__c 
                                                         WHERE Audit_Schedule_Number__c IN:auditScheduleIdSet];
        for(Revision_History__c rev : revisionHistoryList){
            if((rev.Revision__c ==null || String.valueOf(rev.Revision__c) =='') || String.isBlank(rev.Schedule_Change_Reason__c)){
                revisionHistoryWithMandatoryFieldsBlank.add(rev);
            }
        }
        if(revisionHistoryWithMandatoryFieldsBlank.size() >0){
            List<String> revisionHistoryNames = new List<String>();
            for(Revision_History__c rev : revisionHistoryWithMandatoryFieldsBlank){
                revisionHistoryNames.add(rev.Name);
            }
            if(!Test.isRunningTest()){
                newAuditSchedule.values()[0].addError(System.Label.errorMessageForRequiredFieldsIRevisionHistory+revisionHistoryNames);
            }
             
        }
    }
  
  public static void auditsScheduleT(Map<Id, BMX_Audits_Schedule__c> auditSchedulesOld, Map<Id, BMX_Audits_Schedule__c> auditScheduleNew) {
    Id internalRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id externeRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();
      List<Id> auditScheduleIdSets = new List<Id>();

    // Iterate through new audit schedules
    for (BMX_Audits_Schedule__c audits : auditScheduleNew.values()) {
        // Get the corresponding old audit schedule
        BMX_Audits_Schedule__c oldAuditSchedule = auditSchedulesOld.get(audits.Id);

        // Check new audit has Implementation status
        if (oldAuditSchedule != null &&
            oldAuditSchedule.CMPL123_WF_Status__c != System.Label.Status_Audit_Schedule_Implementation &&
            audits.CMPL123_WF_Status__c == System.Label.Status_Audit_Schedule_Implementation) {
            auditScheduleIdSets.add(audits.Id);
        }
    }

    // Query BMX_Quality_Audit__c records related to the Audit Schedules
    List<BMX_Quality_Audit__c> listAuditsInParent = [SELECT Id, CMPL123_WF_Status__c, Audit_Schedule__c 
                                                     FROM BMX_Quality_Audit__c 
                                                     WHERE Audit_Schedule__c IN :auditScheduleIdSets];
    List<BMX_Audits_Schedule__c> listParentQAudit = [SELECT Id,RecordType.DeveloperName,CMPL123Task_Key_Value__c,CMPL123_WF_Status__c 
                                                     FROM BMX_Audits_Schedule__c 
                                                     WHERE Id IN:auditScheduleIdSets];
	Integer count = 0;
    List<Id> listIdScheduleTrue = new List<Id>();
    List<BMX_Audits_Schedule__c> listSchedToUpdate = new List<BMX_Audits_Schedule__c>();
	system.debug('listAuditsInParent:'+listAuditsInParent);
    // Check if listAuditsInParent is not empty
    if (!listAuditsInParent.isEmpty()) {
        for (BMX_Quality_Audit__c qAud : listAuditsInParent) {
            // Check if the status meets certain criteria
            if (qAud.CMPL123_WF_Status__c == Label.Status_Report_Approved ||
                qAud.CMPL123_WF_Status__c == Label.Status_Closed_Cancelled || 
                 qAud.CMPL123_WF_Status__c == Label.Status_Closed_Done){
                     system.debug('enter if AND');
                count ++;
                
            }
        }
        
	system.debug('listIdScheduleTrue:'+listIdScheduleTrue);
        system.debug('count'+ count);
       
    if (count == listAuditsInParent.size()) {
        //listIdScheduleTrue.add(auditScheduleIdSets[0]);
        system.debug('enter listIdScheduleTrue');
        
        // Iterate through the audit schedules to update
        for (BMX_Audits_Schedule__c audSchToUpdate : listParentQAudit) {
            if (audSchToUpdate.RecordTypeId == internalRecordTypeId &&
                audSchToUpdate.CMPL123_WF_Status__c == Label.Status_Audit_Schedule_Implementation) {
                audSchToUpdate.CMPL123Task_Key_Value__c = TASK_VALUE_INTERNAL; 
            } else if (audSchToUpdate.RecordTypeId == externeRecordTypeId &&
                       audSchToUpdate.CMPL123_WF_Status__c == Label.Status_Audit_Schedule_Implementation) {
                	   audSchToUpdate.CMPL123Task_Key_Value__c = TASK_VALUE_EXTERNAL;
            }
            listSchedToUpdate.add(audSchToUpdate);
        }
	system.debug('exit listIdScheduleTrue');
    }

 
}
        If (listSchedToUpdate.size()>0){
            system.debug('in update' + listSchedToUpdate);
       		update listSchedToUpdate;
    }
  }
public static void closeAuditsScheduleAfterQualityAudit(Map<Id, BMX_Audits_Schedule__c> OldauditSchedules, Map<Id, BMX_Audits_Schedule__c> NewAuditSchedules) {
        Id internalRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
            Id externeRecordTypeId = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();
          List<Id> auditScheduleSIdSets = new List<Id>();
    
        // Iterate through new audit schedules
        for (BMX_Audits_Schedule__c auditsSch : NewAuditSchedules.values()) {
            // Get the corresponding old audit schedule
            BMX_Audits_Schedule__c OldauditSchedule = OldauditSchedules.get(auditsSch.Id);
    
            // Check new audit has Implementation status
            if (OldauditSchedule != null &&
            OldauditSchedule.CMPL123_WF_Status__c != System.Label.Status_Audit_Schedule_Executed &&
                auditsSch.CMPL123_WF_Status__c == System.Label.Status_Audit_Schedule_Executed) {
                auditScheduleSIdSets.add(auditsSch.Id);
            }
        }
    
        // Query BMX_Quality_Audit__c records related to the Audit Schedules
        List<BMX_Quality_Audit__c> listQualityAuditsInParent = [SELECT Id, CMPL123_WF_Status__c, Audit_Schedule__c 
                                                         FROM BMX_Quality_Audit__c 
                                                         WHERE Audit_Schedule__c IN :auditScheduleSIdSets];
    List<BMX_Audits_Schedule__c> listParentQAudit = [SELECT Id,RecordType.DeveloperName,CMPL123Task_Key_Value__c,CMPL123_WF_Status__c 
                                                     FROM BMX_Audits_Schedule__c 
                                                     WHERE Id IN:auditScheduleSIdSets];
	Integer count = 0;
        List<Id> listIdScheduleTrue = new List<Id>();
 List<BMX_Audits_Schedule__c> listScheduleToUpdate = new List<BMX_Audits_Schedule__c>();
            // Iterate through the audit schedules to update
    system.debug('listofmyqualityaudit' +listIdScheduleTrue );
        // Check if listAuditsInParent is not empty
        if (!listQualityAuditsInParent.isEmpty()) {
            for (BMX_Quality_Audit__c qAudits : listQualityAuditsInParent) {
                // Check if the status meets certain criteria
                if (qAudits.CMPL123_WF_Status__c == Label.Status_Closed_Cancelled
                    || qAudits.CMPL123_WF_Status__c == Label.Status_Closed_Done
                    ) {
                    count ++;
          
                }
                
            }
        
     system.debug('listidschedule' +listIdScheduleTrue );
        if (count==listQualityAuditsInParent.size()) {
	//listIdScheduleTrue.add(auditScheduleSIdSets[0]);
           
            for (BMX_Audits_Schedule__c audScheduleToUpdate : listParentQAudit) {
                if (audScheduleToUpdate.RecordTypeId == internalRecordTypeId &&
                audScheduleToUpdate.CMPL123_WF_Status__c == Label.Status_Audit_Schedule_Executed) {
                    audScheduleToUpdate.CMPL123Task_Key_Value__c = TASK_VALUE_INTER; 
                } else if (audScheduleToUpdate.RecordTypeId == externeRecordTypeId &&
                audScheduleToUpdate.CMPL123_WF_Status__c == Label.Status_Audit_Schedule_Executed) {
                    audScheduleToUpdate.CMPL123Task_Key_Value__c = TASK_VALUE_EXTER;
                }

                listScheduleToUpdate.add(audScheduleToUpdate);
            }
}
}
If (listScheduleToUpdate.size()>0){
            system.debug('in update' + listScheduleToUpdate);
       		update listScheduleToUpdate;
    }
  }
}