force-app/main/default/objects/BMX_Audits_Schedule__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Quality Audits</relationshipLabel>
    <relationshipName>Quality_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2031</fullName>
    </customValue>
    <customValue>
        <fullName>2032</fullName>
    </customValue>
    <customValue>
        <fullName>2033</fullName>
    </customValue>
    <customValue>
        <fullName>2034</fullName>
    </customValue>
    <customValue>
        <fullName>2035</fullName>
    </customValue>
    <customValue>
        <fullName>2036</fullName>
    </customValue>
    <customValue>
        <fullName>2037</fullName>
    </customValue>
    <customValue>
        <fullName>2038</fullName>
    </customValue>
    <customValue>
        <fullName>2039</fullName>
    </customValue>
    <customValue>
        <fullName>2040</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TestHandler.cls
@isTest
public class TestHandler {

    @TestSetup
    static void makeData() {
        Id internalRecordType = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id externalRecordType = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();

        BMX_Audits_Schedule__c Audits_Schedule = new BMX_Audits_Schedule__c(
            RecordTypeId = internalRecordType,
            Title__c = 'Test Internal',
            Year__c = '2022',
            CMPL123_WF_Status__c = 'Audit Schedule Implementation'
        );
        insert Audits_Schedule;

        BMX_Audits_Schedule__c Audits_Schedule2 = new BMX_Audits_Schedule__c(
            RecordTypeId = externalRecordType,
            Title__c = 'Test',
            Year__c = '2022',
            CMPL123_WF_Status__c = 'Audit Schedule Definition'
        );
        insert Audits_Schedule2;

        BMX_Quality_Audit__c qualityAudit = new BMX_Quality_Audit__c(
            Audit_Schedule__c = Audits_Schedule.Id,
            CMPL123_WF_Status__c = 'Initiated'
        );
        insert qualityAudit;

        BMX_Quality_Audit__c qualityAudit2 = new BMX_Quality_Audit__c(
            Audit_Schedule__c = Audits_Schedule2.Id,
            CMPL123_WF_Status__c = 'Initiated'
        );
        insert qualityAudit2;
    }

    @isTest
    static void testHandleAfterUpdate() {
        Test.startTest();
        makeData(); // Create necessary data

        // Retrieve the created records and call the method to be tested
        List<BMX_Audits_Schedule__c> auditSchedules = [SELECT Id FROM BMX_Audits_Schedule__c];
        Map<Id, BMX_Audits_Schedule__c> newAuditSchedule = new Map<Id, BMX_Audits_Schedule__c>([SELECT Id, CMPL123_WF_Status__c FROM BMX_Audits_Schedule__c WHERE Id IN :auditSchedules]);

        // Create a map with the same records as newAuditSchedule for oldAuditSchedule
        Map<Id, BMX_Audits_Schedule__c> oldAuditSchedule = new Map<Id, BMX_Audits_Schedule__c>(newAuditSchedule);

        // Trigger the handleAfterUpdate method
        Audit_ScheduleTriggerHandler.handleAfterUpdate(oldAuditSchedule, newAuditSchedule);
        Test.stopTest();

        // Verify the changes in Quality Audits
        List<BMX_Quality_Audit__c> updatedQualityAudits = [SELECT Id, CMPL123Task_Key_Value__c FROM BMX_Quality_Audit__c];
        System.assertEquals('MoveAuditsToPreparation', updatedQualityAudits[0].CMPL123Task_Key_Value__c);
    }
}