force-app/main/default/objects/Chapter__c/Chapter__c.object-meta.xml
<CustomObject>
    <label>Chapter</label>
    <nameField>
        <label>Chapter #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chapter__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Chapters</relationshipLabel>
    <relationshipName>Chapters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <label>Source</label>
    <nameField>
        <label>Source Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChapterController.cls
public with sharing class ChapterController {
    @AuraEnabled(cacheable=true)
    public static List<Chapter__c> fetchChaptersBySource(List<Id> selectedSourceId) {
        // Query chapters based on the selected source ID
List<Chapter__c> chapters = [SELECT Id,Name,Source__c 
            FROM Chapter__c
            WHERE Source__c IN:selectedSourceId
        ];
        System.debug('Selected Source ID: ' + selectedSourceId);
        return chapters;
    }
}