force-app/main/default/objects/Audit_Agenda_Item__c/Audit_Agenda_Item__c.object-meta.xml
<CustomObject>
    <label>Audit Agenda Item</label>
    <nameField>
        <label>Timeslot</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Agenda_Item__c/fields/Audit__c.field-meta.xml
<CustomField>
    <fullName>Audit__c</fullName>
    <label>Audit #</label>
    <referenceTo>BMX_Quality_Audit__c</referenceTo>
    <relationshipLabel>Audit Agenda Items</relationshipLabel>
    <relationshipName>Audit_Agenda_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/Audit_Finding__c.object-meta.xml
<CustomObject>
    <label>Audit Finding</label>
    <nameField>
        <displayFormat>AF-{0000000}</displayFormat>
        <label>Audit Finding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Finding__c/fields/Audit__c.field-meta.xml
<CustomField>
    <fullName>Audit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit</label>
    <referenceTo>CMPL123QMS__Internal_Audit__c</referenceTo>
    <relationshipLabel>Audit Findings</relationshipLabel>
    <relationshipName>Audit_Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Audit_Finding__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Audit_Team_Member__c/Audit_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Audit Team Member</label>
    <nameField>
        <displayFormat>ATM-{00000000}</displayFormat>
        <label>Audit Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Team_Member__c/fields/Audit__c.field-meta.xml
<CustomField>
    <fullName>Audit__c</fullName>
    <label>Audit #</label>
    <referenceTo>BMX_Quality_Audit__c</referenceTo>
    <relationshipLabel>Audit Team Members</relationshipLabel>
    <relationshipName>Audit_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Audit_Team_Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Auditor</fullName>
            </value>
            <value>
                <fullName>Auditor</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
            <value>
                <fullName>Technical Expert</fullName>
            </value>
            <value>
                <fullName>Auditor in Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Quality Audits</relationshipLabel>
    <relationshipName>Quality_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Lead_Auditor__c.field-meta.xml
<CustomField>
    <fullName>Lead_Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/AuditAgendaHandler_Test.cls
@isTest
public class AuditAgendaHandler_Test {
    @isTest
    public static void testAuditAgendaHandler() {
        // User initialization
        Profile p = [select id from profile where name='Standard User'];
        
        User u = new User(alias = 'utest', email='utest@email.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id, country='United States',
                          timezonesidkey='America/Los_Angeles', username='utest21@email.com',TWD_Role__c='Audit Participant');
        insert u; 
        
        
        Id InternalASched = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id ExterneASched = Schema.SObjectType.BMX_Audits_Schedule__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();       
        Id InternalQAudit = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get('Internal').getRecordTypeId();
        Id ExternalQAudit = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get('External').getRecordTypeId();

       List<BMX_Audits_Schedule__c> listSchedule = new List<BMX_Audits_Schedule__c>();
       List<BMX_Quality_Audit__c> listQAudit = new List<BMX_Quality_Audit__c>();
       List<Audit_Finding__c> listFindings = new List<Audit_Finding__c>();
       List<Audit_Agenda_Item__c> listAgenda = new List<Audit_Agenda_Item__c>();
       List<Audit_Team_Member__c> listAuditTM = new List <Audit_Team_Member__c>();
        
       BMX_Audits_Schedule__c Audits_Schedule = new BMX_Audits_Schedule__c();     
       Audits_Schedule.RecordTypeId = internalASched;
       Audits_Schedule.Title__c = 'TEST';
       Audits_Schedule.CMPL123_WF_Status__c = 'Audit Schedule Definition';
       listSchedule.add(Audits_Schedule);
       insert listSchedule;
        
       BMX_Quality_Audit__c qualityAudit = new BMX_Quality_Audit__c(
        RecordTypeId = InternalQAudit,
        Audit_Schedule__c = listSchedule[0].Id,
        Lead_Auditor__c = u.Id,
        CMPL123_WF_Status__c = 'Initiated'
        );
       listQAudit.add(qualityAudit);
       insert listQAudit;
        
       Audit_Agenda_Item__c auditAgenda = new Audit_Agenda_Item__c(
       Audit__c = qualityAudit.Id,
       StartTime__c = System.Today(),
       EndTime__c  = System.Today().addDays(10),
       Name = 'Meet' 
       );
       listAgenda.add(auditAgenda); 
       insert listAgenda;
        
       Audit_Team_Member__c auditMember = new Audit_Team_Member__c(
       Audit__c = qualityAudit.Id,
       Role__c = 'Auditor',
       Member__c = userinfo.getuserid()
       );
       listAuditTM.add(auditMember);
	   insert listAuditTM;       
    }     

}