force-app/main/default/objects/Audit_Agenda_Item__c/Audit_Agenda_Item__c.object-meta.xml
<CustomObject>
    <label>Audit Agenda Item</label>
    <nameField>
        <label>Timeslot</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Agenda_Item__c/fields/Audit__c.field-meta.xml
<CustomField>
    <fullName>Audit__c</fullName>
    <label>Audit #</label>
    <referenceTo>BMX_Quality_Audit__c</referenceTo>
    <relationshipLabel>Audit Agenda Items</relationshipLabel>
    <relationshipName>Audit_Agenda_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Audit_Agenda_Item__c/fields/Audited_Subjects__c.field-meta.xml
<CustomField>
    <fullName>Audited_Subjects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Subject(s)</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Audit Agenda Items</relationshipLabel>
    <relationshipName>Audit_Agenda_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Agenda_Item__c/fields/Chapter__c.field-meta.xml
<CustomField>
    <fullName>Chapter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chapter</label>
    <referenceTo>Chapter_to_Agenda__c</referenceTo>
    <relationshipLabel>Audit Agenda Items</relationshipLabel>
    <relationshipName>Audit_Agenda_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Agenda_Item__c/fields/Individuals__c.field-meta.xml
<CustomField>
    <fullName>Individuals__c</fullName>
    <label>Individual(s)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Team_Member__c/Audit_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Audit Team Member</label>
    <nameField>
        <displayFormat>ATM-{00000000}</displayFormat>
        <label>Audit Team Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Team_Member__c/fields/Audit__c.field-meta.xml
<CustomField>
    <fullName>Audit__c</fullName>
    <label>Audit #</label>
    <referenceTo>BMX_Quality_Audit__c</referenceTo>
    <relationshipLabel>Audit Team Members</relationshipLabel>
    <relationshipName>Audit_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Audit_Team_Member__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Auditor</fullName>
            </value>
            <value>
                <fullName>Auditor</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
            <value>
                <fullName>Technical Expert</fullName>
            </value>
            <value>
                <fullName>Auditor in Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Lead_Auditor__c.field-meta.xml
<CustomField>
    <fullName>Lead_Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chapter__c/Chapter__c.object-meta.xml
<CustomObject>
    <label>Chapter</label>
    <nameField>
        <label>Chapter #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AuditAgendaHandler.cls
/*
File Name: AuditAgendaHandler
Test Class: AuditAgendaHandler_Test
Description: public class which is used to handle all the custom functioanlity on Audit Agenda object. 
*/

public class AuditAgendaHandler {
    
    public static void Limit_Update(List <Audit_Agenda_Item__c> newAgenda, Map<Id,Audit_Agenda_Item__c> oldAgenda){      
            Set<Id> qualityAuditIdSet = new Set<Id>();
         for(Audit_Agenda_Item__c agenda : newAgenda){
            if(oldAgenda == null || oldAgenda.get(agenda.Id).Audit__c != agenda.Audit__c || oldAgenda.get(agenda.Id).Name != agenda.Name ||
               oldAgenda.get(agenda.Id).StartTime__c != agenda.StartTime__c || oldAgenda.get(agenda.Id).EndTime__c != agenda.EndTime__c ||
               oldAgenda.get(agenda.Id).Audited_Subjects__c != agenda.Audited_Subjects__c || oldAgenda.get(agenda.Id).Comments__c != agenda.Comments__c ||
			    oldAgenda.get(agenda.Id).Individuals__c != agenda.Individuals__c || oldAgenda.get(agenda.Id).Chapter__c != agenda.Chapter__c               
              ){
                 qualityAuditIdSet.add(agenda.Audit__c);
            }
                 
        }
           
       System.debug('qualityAuditIdSet : '+ qualityAuditIdSet); 
        
        
        Map<Id,BMX_Quality_Audit__c> qualityAuditMap = new Map<Id,BMX_Quality_Audit__c>
															([SELECT Id,Lead_Auditor__c 
															  FROM BMX_Quality_Audit__c 
															  WHERE Id IN:qualityAuditIdSet]);

        Map<Id,User> currentUser = new Map<Id,User>
									 ([SELECT Id,TWD_Role__c 
									  FROM User 
									  WHERE Id =: Userinfo.getUserId()]);

       Map<Id,Audit_Team_Member__c> auditTeamMemberMap = new Map<Id,Audit_Team_Member__c>
														([SELECT Id,Audit__c,Role__c,Member__c 
													     FROM Audit_Team_Member__c 
													     WHERE Audit__c IN: qualityAuditIdSet 
													     AND Role__c ='Auditor']);
           	System.debug('qualityAuditList : '+qualityAuditMap);
            System.debug('currentUser : '+currentUser);

    		List<Audit_Team_Member__c> auditTeamMemberList = new List<Audit_Team_Member__c>();
            for(Audit_Team_Member__c atm : auditTeamMemberMap.values()){
                        if(atm.Member__c == userinfo.getuserid()){
                            System.debug('Member__c:'+atm.Member__c);
                            System.debug('getuserid:'+userinfo.getuserid());
                            auditTeamMemberList.add(atm);
                        }
                    }
        User userC = currentUser.get(userinfo.getuserid());
            for(Audit_Agenda_Item__c agenda : newAgenda){
               IF(!qualityAuditMap.isEmpty()){
                if(qualityAuditMap.get(agenda.Audit__c).Lead_Auditor__c != userinfo.getuserid() && !userC.TWD_Role__c.contains ('Audit Coordinator') && auditTeamMemberList.size() < 1){
                    //System.debug('getuserid:'+userinfo.getuserid());
                    if(!Test.isRunningTest()){
                    newAgenda[0].addError(System.Label.Audit_Agenda_Limit_Edit_Error);
                    }
                }
              } 
            }
        }

}