force-app/main/default/objects/Audit_Finding__c/Audit_Finding__c.object-meta.xml
<CustomObject>
    <label>Audit Finding</label>
    <nameField>
        <displayFormat>AF-{0000000}</displayFormat>
        <label>Audit Finding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Finding__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/fields/Finding_Type__c.field-meta.xml
<CustomField>
    <fullName>Finding_Type__c</fullName>
    <label>Finding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clinical</fullName>
                <isActive>false</isActive>
                <label>Clinical</label>
            </value>
            <value>
                <fullName>Deviation</fullName>
                <isActive>false</isActive>
                <label>Deviation</label>
            </value>
            <value>
                <fullName>EHS/Facilities</fullName>
                <isActive>false</isActive>
                <label>EHS/Facilities</label>
            </value>
            <value>
                <fullName>Non conformance</fullName>
                <isActive>false</isActive>
                <label>Non conformance</label>
            </value>
            <value>
                <fullName>Non-Conformity</fullName>
            </value>
            <value>
                <fullName>OOS</fullName>
                <isActive>false</isActive>
                <label>OOS</label>
            </value>
            <value>
                <fullName>OOT</fullName>
                <isActive>false</isActive>
                <label>OOT</label>
            </value>
            <value>
                <fullName>Opportunity for Improvement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Process</fullName>
                <isActive>false</isActive>
                <label>Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/fields/Nonconformity_Grading__c.field-meta.xml
<CustomField>
    <fullName>Nonconformity_Grading__c</fullName>
    <label>Non-Conformity Grading</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Finding_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/fields/Nonconformity_Type__c.field-meta.xml
<CustomField>
    <fullName>Nonconformity_Type__c</fullName>
    <label>Non-Conformity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Finding_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/fields/Parent_Audit__c.field-meta.xml
<CustomField>
    <fullName>Parent_Audit__c</fullName>
    <label>Parent Audit #</label>
    <referenceTo>BMX_Quality_Audit__c</referenceTo>
    <relationshipLabel>Audit Findings</relationshipLabel>
    <relationshipName>Audit_Findings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Audit_Finding__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Audit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Audit_Schedule__c</fullName>
    <label>Audit Schedule #</label>
    <referenceTo>BMX_Audits_Schedule__c</referenceTo>
    <relationshipLabel>Quality Audits</relationshipLabel>
    <relationshipName>Quality_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Lead_Auditor__c.field-meta.xml
<CustomField>
    <fullName>Lead_Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/BMX_Quality_Audit__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/QualityAuditsHelperTest.cls
@isTest
public class QualityAuditsHelperTest {
        
    // Create record types for test data
        RecordType internalRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'BMX_Audits_Schedule__c' AND DeveloperName = 'Internal' LIMIT 1];
        RecordType externalRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'BMX_Audits_Schedule__c' AND DeveloperName = 'External' LIMIT 1];
          
    @isTest
    static void testAuditStatusChange() {
        // Create test data
         RecordType internalRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'BMX_Audits_Schedule__c' AND DeveloperName = 'Internal' LIMIT 1];
         BMX_Audits_Schedule__c auditSchedule1 = new BMX_Audits_Schedule__c(
            RecordTypeId = internalRecordType.Id,
            Title__c = 'Test Internal',
            CMPL123_WF_Status__c = 'Audit Schedule Executed'
       );
        insert auditSchedule1;
        
        auditSchedule1.CMPL123_WF_Status__c = Label.Status_Audit_Schedule_Implementation;
        update auditSchedule1;
        
       BMX_Quality_Audit__c qualityAudit1 = new BMX_Quality_Audit__c(
            Audit_Schedule__c = auditSchedule1.Id,
            CMPL123_WF_Status__c = Label.Status_Closed_Cancelled
        );
        insert qualityAudit1;
        BMX_Quality_Audit__c qualityAudit2 = new BMX_Quality_Audit__c(
            Audit_Schedule__c = auditSchedule1.Id,
            CMPL123_WF_Status__c = 'Initiated'
        );
        insert qualityAudit2;

        Test.startTest();
        qualityAudit2.CMPL123_WF_Status__c = Label.Status_Closed_Cancelled;
        update qualityAudit2;
        QualityAuditsMoveAuditsScheduleHelper.moveAuditSchedule(new Set<Id>{qualityAudit2.Audit_Schedule__c});
        Test.stopTest();

	   
    }
    
	 @isTest
    static void testCheckFindings() {
         
        Profile admin = [select id from profile where name='System Administrator'];
        
        User usr = new User(alias = 'utest', emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = admin.Id, country='United States',
                          timezonesidkey='America/Los_Angeles', email='utest@email.com',
                          username='utest21@email.com',TWD_Role__c='Audit Coordinator'); 
        insert usr; 
        
        System.runAs(usr){
        Id externalIdRecordType = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get(Label.External_Record_Type).getRecordTypeId();
        Id internalIdRecordType = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get(Label.Internal_Record_Type).getRecordTypeId();
        RecordType internalRecordTypeAS = [SELECT Id FROM RecordType WHERE SObjectType = 'BMX_Audits_Schedule__c' AND DeveloperName = 'Internal' LIMIT 1];
        RecordType internalRecordTypeAF = [SELECT Id FROM RecordType WHERE SObjectType = 'Audit_Finding__c' AND DeveloperName = 'Internal' LIMIT 1];
        
       List<BMX_Audits_Schedule__c> listSchedule = new List<BMX_Audits_Schedule__c>();
       List<BMX_Quality_Audit__c> listQAudit = new List<BMX_Quality_Audit__c>();
       List<Audit_Finding__c> listFindings = new List<Audit_Finding__c>();
       Set<Id> setAuditId = new Set<Id>();
         
          BMX_Audits_Schedule__c auditSchedule = new BMX_Audits_Schedule__c(
            RecordTypeId = internalRecordTypeAS.Id,
            Title__c = 'Test Internal Check',
            CMPL123_WF_Status__c = 'Initiated'
        );
        listSchedule.add(auditSchedule);
        insert listSchedule;
               
       BMX_Quality_Audit__c qualityAuditCheck = new BMX_Quality_Audit__c(
            RecordTypeId = internalIdRecordType,
            Audit_Schedule__c = listSchedule[0].Id,
            Lead_Auditor__c = usr.Id,
            CMPL123_WF_Status__c = 'Initiated',
            CMPL123_WF_Action__c = 'Notification Approval'
        );
       listQAudit.add(qualityAuditCheck);
       insert listQAudit;
       qualityAuditCheck.CMPL123_WF_Status__c = 'Audit Report Preparation';
       qualityAuditCheck.CMPL123_WF_Action__c = Label.WF_Action_Report_Ready_Approval;
	   update listQAudit;  
        
       Audit_Finding__c auditFinding = new Audit_Finding__c();
       auditFinding.RecordTypeId = internalRecordTypeAF.Id;
       auditFinding.Parent_Audit__c = listQAudit[0].id;
       auditFinding.Title__c = 'Test Finding Check';
       auditFinding.Finding_Type__c = 'Non-Conformity';
       auditFinding.Nonconformity_Grading__c = '1';  
       auditFinding.Nonconformity_Type__c = 'Major';
       auditFinding.Assigned_To__c = usr.Id; 
       listFindings.add(auditFinding);
      insert listFindings;
      
      For(BMX_Quality_Audit__c qaud : listQAudit){
           setAuditId.add(qaud.Id);
         }     
            
     QualityAuditCheckFindings.checkFindings(setAuditId, listQAudit);
            
        }       
        
    }
}