force-app/main/default/objects/Audit_Finding__c/Audit_Finding__c.object-meta.xml
<CustomObject>
    <label>Audit Finding</label>
    <nameField>
        <displayFormat>AF-{0000000}</displayFormat>
        <label>Audit Finding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Finding__c/fields/Cause_Investigation__c.field-meta.xml
<CustomField>
    <fullName>Cause_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cause Investigation #</label>
    <referenceTo>Cause_Investigation__c</referenceTo>
    <relationshipLabel>Audit Findings</relationshipLabel>
    <relationshipName>Audit_Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AddendumHelper.cls
public with sharing class AddendumHelper {
    //test sfdx deploy
    //test git diff
    private static List<String> LIST_OF_FIELDS_TO_CHECK = new List<String>{'Audit_Finding__c','BMX_Audits_Schedule__c','BMX_Quality_Audit__c','Change_Request__c','QMS_Task__c','Risk_File_Review__c','Correction__c','CAPA_Action__c','CAPA__c','Cause_Investigation__c','Quality_Event__c'};
    
    public static void checkOnlyOneParent(List<Addendum__c> newElements){
        Helper.checkOnlyOneParent(newElements, LIST_OF_FIELDS_TO_CHECK, Label.ADDENDUM_EVENT_ONLY_ONE_PARENT_AND_MANDATORY);
    }
}