force-app/main/default/objects/Audit_Finding__c/Audit_Finding__c.object-meta.xml
<CustomObject>
    <label>Audit Finding</label>
    <nameField>
        <displayFormat>AF-{0000000}</displayFormat>
        <label>Audit Finding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Finding__c/fields/Action_Plan_Definition_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Definition_Due_Date__c</fullName>
    <label>Action Plan Definition Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/fields/Distributor_Finding_Category__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Finding_Category__c</fullName>
    <label>Distributor Finding Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Complaint handling</fullName>
            </value>
            <value>
                <fullName>Customer Service Activities</fullName>
            </value>
            <value>
                <fullName>HR &amp; Training;RA activities</fullName>
            </value>
            <value>
                <fullName>Logistics &amp; Transport;QMS</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>Sales Admin</fullName>
            </value>
            <value>
                <fullName>Vigilance &amp; FA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Finding__c/fields/Parent_Audit__c.field-meta.xml
<CustomField>
    <fullName>Parent_Audit__c</fullName>
    <label>Parent Audit #</label>
    <referenceTo>BMX_Quality_Audit__c</referenceTo>
    <relationshipLabel>Audit Findings</relationshipLabel>
    <relationshipName>Audit_Findings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BMX_Quality_Audit__c/BMX_Quality_Audit__c.object-meta.xml
<CustomObject>
    <label>Quality Audit</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BMX_Quality_Audit__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QualityAuditCheckFindings.cls
public class QualityAuditCheckFindings {
        
     public static void QauditBeforeUpdate(Map<Id, BMX_Quality_Audit__c> oldQualityAudit, Map<Id, BMX_Quality_Audit__c> newQualityAudit){
        Set<Id> setAuditId = new Set<Id>();
        Id externalIdRecordType = Schema.SObjectType.BMX_Quality_Audit__c.getRecordTypeInfosByDeveloperName().get(Label.External_Record_Type).getRecordTypeId();
         For(BMX_Quality_Audit__c Qaudit : newQualityAudit.values()){
            if((oldQualityAudit.get(Qaudit.Id).CMPL123_WF_Action__c != Label.WF_Action_Report_Ready_Approval && Qaudit.CMPL123_WF_Action__c==Label.WF_Action_Report_Ready_Approval)
                && Qaudit.RecordTypeId == externalIdRecordType){
                setAuditId.add(Qaudit.Id);
            }
        }
        System.debug('setAuditId : ' + setAuditId);
        checkFindings(setAuditId,newQualityAudit.values());
        }
     
  public static void checkFindings(Set<Id> setQualityAuditId, list<BMX_Quality_Audit__c>newQualityAuditValues) {
   List<Audit_Finding__c> listFindingsBlankFields = new List<Audit_Finding__c>(); 
   List<String> findingNames = new List<String>();
   List<Audit_Finding__c> listRelatedFindings = [SELECT Id,Name,Parent_Audit__c,Distributor_Finding_Category__c, 
                                                 Scope__c, Action_Plan_Definition_Due_Date__c,Recordtype.Name 
                                                 FROM Audit_Finding__c 
                                                 WHERE Parent_Audit__c IN: setQualityAuditId
                                                 AND Recordtype.Name =: Label.External_Record_Type
                                                 ];
 
   IF(listRelatedFindings.size()>0){
     for(Audit_Finding__c finding : listRelatedFindings){
        if(finding.Action_Plan_Definition_Due_Date__c==null){   
          listFindingsBlankFields.add(finding);
            }
          if (finding.Scope__c== Label.Scope_Distributor_Value && String.isBlank(finding.Distributor_Finding_Category__c)){
              listFindingsBlankFields.add(finding);
         }
     }
   }
      If(listFindingsBlankFields.size() > 0){
            for(Audit_Finding__c find : listFindingsBlankFields){
                findingNames.add(find.Name);
            }
          newQualityAuditValues[0].addError(Label.error_Message_Mandatory_Fields_In_Finding+'\n'+'for Audit Findings:' + findingNames); 
        }
         
     }        
}